### ISSUE TITLE
trainNetwork method in model_train.py is defined wrongly

### ISSUE THREAD

**Issue by hiteshpindikanti** [2021rahul/colorization_tensorflow#2]
The trainNetwork method in the file model_train.py has something wrong with it.
1)  I think the method is copied from the Automated_fappy repository. The code here is mixed with the code of that repository.
2) After resolving the above issue. The method intends to train the basic cifar-10 model instead of training the actual model defined in build_model.py file

**Comment by 2021rahul** [comment]
Code modified. Working fine
